apiVersion: v1
kind: Pod
metadata:
  name: test-bad-registry
  namespace: demo
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
  - name: app
    image: docker.io/nginx:1.25.3
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
