# PASS: Pod hợp lệ — vượt qua cả 4 luật
apiVersion: v1
kind: Pod
metadata:
  name: test-pass-valid
  namespace: demo
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
  - name: app
    image: nginx:1.25.3
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
